server:
  port: 9527

spring:
  application:
    name: cloud-gateway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，服务有多个提供者,利用微服务名进行路由
      routes:
        - id: payment_routh                   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://192.168.3.42:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路由规则

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://192.168.3.42:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- XHeader=-Request-Id, \d+  # 请求头要有X-Reque`st-Id属性并且值为整数的正则表达式
          filters:



eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527  #实例ID的显示
    prefer-ip-address: true   #访问路径显示IP地址

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
