server:
  port: 8002

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #使用Druid数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      validation-query: SELECT 1


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunflower.entities



eureka:
  client:
    #是否在EurekaServer抓自己的注册信息,默认true,单节点无所谓,集群下必须开启,才可以配合ribbon实现负载均衡
    fetch-registry: true
    #表自己注册进入eureka注册中心
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002  #实例ID的显示
    prefer-ip-address: true   #访问路径显示IP地址
