server:
  port: 7001

spring:
  application:
    name: Eureka-Payment-01


eureka:
  instance:
    hostname: eureka7001.com  # eureka服务端

  client:
    register-with-eureka: false # eureka服务端不用注册自己
    fetch-registry: false #表示自己就是注册中心
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/   #集群下,以另一台作为注册中心
      defaultZone: http://eureka7001.com:7001/eureka/   #单机,就是7001自己